import type { ReactNode } from "react";
import Script from "next/script";
import "./globals.css";

export const metadata = {
  title: "Permit-buddy",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <head>
        <Script id="theme-preload" strategy="beforeInteractive">
          {`(function(){
  try {
    var root = document.documentElement;
    var stored = localStorage.getItem('permit-buddy-theme');
    var systemDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
    if (stored === 'dark' || ((!stored || stored === 'system') && systemDark)) {
      root.classList.add('dark');
    } else {
      root.classList.remove('dark');
    }
  } catch (error) {
    console.warn('Theme preload failed', error);
  }
})();`}
        </Script>
      </head>
      <body className="min-h-screen bg-slate-100 text-slate-900 antialiased transition-colors duration-300 dark:bg-slate-950 dark:text-slate-100">
        {children}
      </body>
    </html>
  );
}
